# Generated by Django 4.2.3 on 2023-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_budget_created_at_alter_budget_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
