# Generated by Django 4.2.3 on 2023-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Budget description'),
        ),
    ]
